---
# (py)nslcd aka nss-pam-ldapd
#-----------------------------------------------------------------------

- name: "Install packages for {{ nslcd_package_name }}"
  apt:
    name: "{{ item }}"
    state: installed
    install_recommends: no
    update_cache: yes
    dpkg_options: 'force-confold,force-confdef'
  with_items:
    - "{{ nslcd_package_name }}"
    - nscd
    - libpam-ldapd
    - libnss-ldapd

- name: "Create {{ nslcd_conf_file }}"
  template:
    src: "nslcd.conf.j2"
    dest: "{{ nslcd_conf_file }}"
    owner: root
    group: root
    mode: 0600
  notify:
  - restart "{{ nslcd_package_name }}"

- name: "Create {{ nscd_conf_file }}"
  template:
    src: "nscd.conf.j2"
    dest: "{{ nscd_conf_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
  - restart nscd

- name: ensure "{{ nslcd_package_name }}" is running (and enable it at boot)
  service: name="{{ nslcd_package_name }}" state=started enabled=yes

- name: ensure nscd is running (and enable it at boot)
  service: name=nscd state=started enabled=yes

# sudo
#-----------------------------------------------------------------------

- name: Install sudo-ldap
  apt: name=sudo-ldap state=installed install_recommends=no dpkg_options='force-confold,force-confdef'

- name: Create sudo-ldap.conf
  template: src="sudo-ldap.conf.j2" dest="/etc/sudo-ldap.conf" owner=root group=root mode=0600

