---
# nslcd aka nss-pam-ldapd
#-----------------------------------------------------------------------

- name: "Install packages for {{ nslcd_package_name }} on {{ lsb_id }}"
  zypper:
    name:
      - nss-pam-ldapd
      - sudo
    state: present
    disable_recommends: yes
    type: package
