---

- name: "Install sssd-ldap, PAM/NSS, LDAP backend and sudo packages"
  zypper:
    name:
      - sssd
      - sssd-ldap
      - sudo
    state: latest
    disable_recommends: yes
    type: package
  notify:
  - restart sssd
