---

- name: "Install sssd-ldap, PAM/NSS and LDAP backend packages"
  apt:
    name:
      - sssd-common
      - sssd-ldap
      - sssd-krb5-common
      - python-sss
      - libnss-sss
      - libpam-sss
      - libsss-sudo
    state: present
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    dpkg_options: 'force-confold,force-confdef'
  notify:
  - restart sssd
 
- name: "Install normal sudo"
  apt: name=sudo state=installed install_recommends=no dpkg_options='force-confold,force-confdef'
