---
# sssd

- name: "Install caching demon for module {{ nsswitch_module }} on {{ ansible_lsb.id }}"
  include: "{{ nsswitch_module }}-{{ ansible_lsb.id }}.yml"

- name: "Create sssd.conf"
  template:
    src: "sssd.conf.j2"
    dest: "{{ sssd_conf_file }}"
    owner: root
    group: root
    mode: 0600
  notify:
  - restart sssd

- name: "ensure sssd is running"
  service: name=sssd state=started enabled=yes

