---
# handlers file for roles/ae-linux-login

- name: restart sssd
  service: name=sssd state=restarted
  when: nsswitch_module=="sss"

- name: restart "{{ nslcd_package_name }}"
  service: name="{{ nslcd_package_name }}" state=restarted
  when: nsswitch_module=="ldap"

- name: restart nscd
  service: name=nscd state=restarted

- name: "restart sshd"
  service: name="{{ sshd_service_name[ansible_lsb.id] }}" state=restarted

